In [46]:
from PyNaver import Datalab
import pandas as pd
from datetime import datetime

import time

In [41]:
# API 인증 정보 설정
client_id = "bfyYjqp9aeVgez9TWrQm"
client_secret = "pirblBFcyM"

# 네이버 데이터랩 API 세션 정의
DL = Datalab(client_id, client_secret)

In [30]:
name_list = list(data['영화명'])
date_list = list(data['개봉일'])

In [43]:
date_list[0]

Timestamp('2019-01-23 00:00:00')

In [35]:
datetime.strptime(date_list[1], '%Y-%m-%d').day

TypeError: strptime() argument 1 must be str, not Timestamp

In [38]:
data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:2/Movie_Project/데이터 전처리/영화 제목 및 정보 main_dataset_10_3.xlsx')

name_list = list(data['영화명'])
date_list = list(data['개봉일'])

final_list = []



# 요청 파라미터 설정

for i in range(len(name_list[:5])):
    name = name_list[i]
    startDate = date_list[i]
    f_year = startDate.year
    f_month = startDate.month + 1
    if f_month == 13:
        f_month = 1 
        f_year += 1 
    time.sleep(0.5) 
    f_date = startDate.day
    endDate = str(f_year) + '-' + str(f_month) + '-' + str(f_date) 
    startDate = str(startDate.year) + '-' + str(startDate.month) + '-' + str(startDate.day)
    timeUnit = 'date'
    device = ''
    ages = []
    gender = ''
    
    keyword_group_set = {
        'keyword_group_1': {'groupName': name, 'keywords': [name]},
    }

    # 검색어 그룹 세트 등록하기
    DL.add_keyword_groups(keyword_group_set['keyword_group_1'])

    df = DL.get_data(startDate, endDate, timeUnit, device, ages, gender)

HTTPError: HTTP Error 400: Bad Request

In [19]:
# 검색어 그룹 세트 정의하기
keyword_group_set = {
    'keyword_group_1': {'groupName': "탑건", 'keywords': ["탑건"]},
}

SyntaxError: invalid syntax (1332914504.py, line 3)

In [47]:
# 요청 파라미터 설정
startDate = "2019-01-23"
endDate = "2019-02-23"
timeUnit = 'month'
device = ''
ages = []
gender = ''





# 검색어 그룹 세트 등록하기
DL.add_keyword_groups(keyword_group_set['keyword_group_1'])

/Users/dongyokim/miniforge3/envs/crawl/lib/python3.9/site-packages/PyNaver/api.py:73: FutureWarning: Passing 'suffixes' which cause duplicate columns {'극한직업_x'} in the result is deprecated and will raise a MergeError in a future version.
  df = pd.merge(df, tmp, how='left', on=['period'])

           날짜     극한직업_x     극한직업_y     극한직업_x     극한직업_y
0  2019-01-23   40.86066   40.86066   40.86066   40.86066
1  2019-01-24   50.60997   50.60997   50.60997   50.60997
2  2019-01-25   44.77352   44.77352   44.77352   44.77352
3  2019-01-26   68.18710   68.18710   68.18710   68.18710
4  2019-01-27   68.15644   68.15644   68.15644   68.15644
5  2019-01-28   56.19940   56.19940   56.19940   56.19940
6  2019-01-29   41.43248   41.43248   41.43248   41.43248
7  2019-01-30   47.68731   47.68731   47.68731   47.68731
8  2019-01-31   40.18622   40.18622   40.18622   40.18622
9  2019-02-01   40.64413   40.64413   40.64413   40.64413
10 2019-02-02   55.50173   55.50173   55.50173   55.50173
11 2019-02-03   64.94723   64.94723   64.94723   64.94723
12 2019-02-04   65.97130   65.97130   65.97130   65.97130
13 2019-02-05   78.52598   78.52598   78.52598   78.52598
14 2019-02-06  100.00000  100.00000  100.00000  100.00000
15 2019-02-07   67.69305   67.69305   67.69305   67.69305
16 2019-02-08   47.55323   47.55323   47.55323   47.55323
17 2019-02-09   52.61118   52.61118   52.61118   52.61118
18 2019-02-10   49.00762   49.00762   49.00762   49.00762
19 2019-02-11   40.47810   40.47810   40.47810   40.47810
20 2019-02-12   28.68935   28.68935   28.68935   28.68935
21 2019-02-13   25.91254   25.91254   25.91254   25.91254
22 2019-02-14   26.60682   26.60682   26.60682   26.60682
23 2019-02-15   25.42672   25.42672   25.42672   25.42672
24 2019-02-16   29.50964   29.50964   29.50964   29.50964
25 2019-02-17   31.01083   31.01083   31.01083   31.01083
26 2019-02-18   24.58868   24.58868   24.58868   24.58868
27 2019-02-19   20.62177   20.62177   20.62177   20.62177
28 2019-02-20   19.11413   19.11413   19.11413   19.11413
29 2019-02-21   17.67522   17.67522   17.67522   17.67522
30 2019-02-22   17.17827   17.17827   17.17827   17.17827
31 2019-02-23   22.56779   22.56779   22.56779   22.56779

In [48]:
# 결과 데이터를 DataFrame으로 조회하기
DL.get_data(startDate, endDate, timeUnit, device, ages, gender)

/Users/dongyokim/miniforge3/envs/crawl/lib/python3.9/site-packages/PyNaver/api.py:73: FutureWarning: Passing 'suffixes' which cause duplicate columns {'극한직업_x'} in the result is deprecated and will raise a MergeError in a future version.
  df = pd.merge(df, tmp, how='left', on=['period'])

           날짜     극한직업_x     극한직업_y     극한직업_x     극한직업_y
0  2019-01-23   40.86066   40.86066   40.86066   40.86066
1  2019-01-24   50.60997   50.60997   50.60997   50.60997
2  2019-01-25   44.77352   44.77352   44.77352   44.77352
3  2019-01-26   68.18710   68.18710   68.18710   68.18710
4  2019-01-27   68.15644   68.15644   68.15644   68.15644
5  2019-01-28   56.19940   56.19940   56.19940   56.19940
6  2019-01-29   41.43248   41.43248   41.43248   41.43248
7  2019-01-30   47.68731   47.68731   47.68731   47.68731
8  2019-01-31   40.18622   40.18622   40.18622   40.18622
9  2019-02-01   40.64413   40.64413   40.64413   40.64413
10 2019-02-02   55.50173   55.50173   55.50173   55.50173
11 2019-02-03   64.94723   64.94723   64.94723   64.94723
12 2019-02-04   65.97130   65.97130   65.97130   65.97130
13 2019-02-05   78.52598   78.52598   78.52598   78.52598
14 2019-02-06  100.00000  100.00000  100.00000  100.00000
15 2019-02-07   67.69305   67.69305   67.69305   67.69305
16 2019-02-08   47.55323   47.55323   47.55323   47.55323
17 2019-02-09   52.61118   52.61118   52.61118   52.61118
18 2019-02-10   49.00762   49.00762   49.00762   49.00762
19 2019-02-11   40.47810   40.47810   40.47810   40.47810
20 2019-02-12   28.68935   28.68935   28.68935   28.68935
21 2019-02-13   25.91254   25.91254   25.91254   25.91254
22 2019-02-14   26.60682   26.60682   26.60682   26.60682
23 2019-02-15   25.42672   25.42672   25.42672   25.42672
24 2019-02-16   29.50964   29.50964   29.50964   29.50964
25 2019-02-17   31.01083   31.01083   31.01083   31.01083
26 2019-02-18   24.58868   24.58868   24.58868   24.58868
27 2019-02-19   20.62177   20.62177   20.62177   20.62177
28 2019-02-20   19.11413   19.11413   19.11413   19.11413
29 2019-02-21   17.67522   17.67522   17.67522   17.67522
30 2019-02-22   17.17827   17.17827   17.17827   17.17827
31 2019-02-23   22.56779   22.56779   22.56779   22.56779