In [48]:
import pandas as pd
import numpy as np
import openpyxl

In [49]:
data = pd.read_excel('/Users/dongyokim/main/jupyter/2022:2/Movie_Project/데이터 원본/KOBIS_개봉일람_2022-09-26.xlsx', skiprows=[0, 1, 2, 3, 4])

In [50]:
data.rename(columns={'전국.1':'전국 매출액', '전국.2':'전국 관객수', '서울':'서울 매출액', '서울.1':'서울 관객수'}, inplace=True)

In [51]:
data.drop(0, axis=0, inplace=True)

In [52]:
# 인덱
data.reset_index(drop=True, inplace=True)

In [53]:
data.head()

,순번,영화명,감독,제작사,수입사,배급사,개봉일,영화유형,영화형태,국적,전국,전국 매출액,전국 관객수,서울 매출액,서울 관객수,장르,등급,영화구분
0,1.0,극한직업,이병헌,"(주)어바웃잇,영화사 해그림 주식회사,(주)씨제이이엔엠",NaN,(주)씨제이이엔엠,2019-01-23,개봉영화,장편,한국,1978,139647979516,16264944,31858660536,3638287,코미디,15세이상관람가,일반영화
1,2.0,어벤져스: 엔드게임,"안소니 루소,조 루소",NaN,월트디즈니컴퍼니코리아 유한책임회사,월트디즈니컴퍼니코리아 유한책임회사,2019-04-24,개봉영화,장편,미국,2835,122182694160,13934592,33577136860,3597963,액션,12세이상관람가,일반영화
2,3.0,겨울왕국 2,"크리스 벅,제니퍼 리",NaN,월트디즈니컴퍼니코리아 유한책임회사,월트디즈니컴퍼니코리아 유한책임회사,2019-11-21,개봉영화,장편,미국,2648,114810421450,13747792,28824682580,3225974,애니메이션,전체관람가,일반영화
3,4.0,범죄도시 2,이상용,"주식회사 빅펀치픽쳐스,(주)홍필름,(주)비에이엔터테인먼트",NaN,"주식회사 에이비오엔터테인먼트,메가박스중앙(주)플러스엠",2022-05-18,개봉영화,장편,한국,2498,131293186879,12692947,29072018770,2755693,범죄,15세이상관람가,일반영화
4,5.0,알라딘,가이 리치,NaN,월트디즈니컴퍼니코리아 유한책임회사,월트디즈니컴퍼니코리아 유한책임회사,2019-05-23,개봉영화,장편,미국,1311,106983620359,12555894,30218911039,3377404,어드벤처,전체관람가,일반영화

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8860 entries, 0 to 8859
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   순번      8860 non-null   float64
 1   영화명     8860 non-null   object
 2   감독      7756 non-null   object
 3   제작사     3502 non-null   object
 4   수입사     4059 non-null   object
 5   배급사     8845 non-null   object
 6   개봉일     8860 non-null   datetime64[ns]
 7   영화유형    8860 non-null   object
 8   영화형태    8860 non-null   object
 9   국적      8860 non-null   object
 10  전국      8860 non-null   object
 11  전국 매출액  8860 non-null   object
 12  전국 관객수  8860 non-null   object
 13  서울 매출액  8860 non-null   object
 14  서울 관객수  8860 non-null   object
 15  장르      8807 non-null   object
 16  등급      8860 non-null   object
 17  영화구분    8860 non-null   object
dtypes: datetime64[ns](1), float64(1), object(16)
memory usage: 1.2+ MB

In [55]:
# 2022-07월 이후에 개봉한 영화 출력후 삭제


delete_index = list(data[data['개봉일'] >= '2022-07-01'].index)
data[data['개봉일'] >= '2022-07-01']

,순번,영화명,감독,제작사,수입사,배급사,개봉일,영화유형,영화형태,국적,전국,전국 매출액,전국 관객수,서울 매출액,서울 관객수,장르,등급,영화구분
14,15.0,한산: 용의 출현,김한민,(주)빅스톤픽쳐스,NaN,롯데컬처웍스(주)롯데엔터테인먼트,2022-07-27,개봉영화,장편,한국,2223,72036110885,7072065,15536401911,1464122,액션,12세이상관람가,일반영화
35,36.0,헌트,이정재,"(주)아티스트스튜디오,(주)사나이픽처스",NaN,메가박스중앙(주)플러스엠,2022-08-10,개봉영화,장편,한국,1625,40017993174,3879071,9707821757,921430,액션,15세이상관람가,일반영화
60,61.0,토르: 러브 앤 썬더,타이카 와이티티,NaN,월트디즈니컴퍼니코리아 유한책임회사,월트디즈니컴퍼니코리아 유한책임회사,2022-07-06,개봉영화,장편,미국,2143,29493984122,2715633,8442671673,729754,액션,12세이상관람가,일반영화
75,76.0,미니언즈2,카일 발다,NaN,유니버설픽쳐스인터내셔널 코리아(유),유니버설픽쳐스인터내셔널 코리아(유),2022-07-20,개봉영화,장편,미국,1394,21809513839,2249135,4437377202,433143,애니메이션,전체관람가,일반영화
83,84.0,비상선언,한재림,"(주)매그넘나인,(주)씨제스엔터테인먼트,씨네주 유한회사",NaN,(주)쇼박스,2022-08-03,개봉영화,장편,한국,1734,20664923736,2030401,4535633757,429892,드라마,12세이상관람가,일반영화
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8788,8789.0,18학번 박아라,한승희,영화사 레드카펫,NaN,주식회사 루믹스미디어,2022-08-24,개봉영화,장편,한국,1,1000,1,0,0,성인물(에로),청소년관람불가,일반영화
8802,8803.0,2대1 출장녀,김지석,(주)영화사가을,NaN,(주)영화사가을,2022-08-21,개봉영화,장편,한국,1,6000,1,0,0,성인물(에로),청소년관람불가,일반영화
8804,8805.0,2대2 할래?,민병관,(주)영화사가을,NaN,(주)영화사가을,2022-07-25,개봉영화,장편,한국,1,6000,1,0,0,성인물(에로),청소년관람불가,일반영화
8846,8847.0,F컵여동생과의정사-무삭제,이정석,스마일컨텐츠,NaN,스마일컨텐츠,2022-08-10,개봉영화,장편,한국,1,1000,1,0,0,멜로/로맨스,청소년관람불가,일반영화
8847,8848.0,G컵 거유 여대생의 오일마사지,NaN,NaN,NaN,(주)픽쳐레스크,2022-07-21,개봉영화,장편,일본,1,1000,1,0,0,멜로/로맨스,청소년관람불가,일반영화

In [56]:
list(delete_index)

[14,
 35,
 60,
 75,
 83,
 112,
 187,
 234,
 240,
 262,
 307,
 396,
 443,
 491,
 517,
 521,
 571,
 640,
 663,
 674,
 759,
 766,
 812,
 838,
 850,
 867,
 898,
 902,
 996,
 1093,
 1163,
 1181,
 1202,
 1226,
 1271,
 1397,
 1415,
 1470,
 1505,
 1538,
 1540,
 1546,
 1553,
 1573,
 1647,
 1684,
 1754,
 1776,
 1834,
 1915,
 1951,
 1960,
 1978,
 2077,
 2129,
 2130,
 2138,
 2177,
 2203,
 2266,
 2283,
 2310,
 2359,
 2362,
 2367,
 2369,
 2484,
 2493,
 2504,
 2505,
 2521,
 2528,
 2583,
 2726,
 2776,
 2881,
 2921,
 2925,
 3066,
 3073,
 3089,
 3101,
 3103,
 3113,
 3128,
 3131,
 3132,
 3133,
 3152,
 3222,
 3252,
 3673,
 3677,
 3731,
 3782,
 3877,
 3878,
 3882,
 3889,
 3892,
 3904,
 3905,
 3906,
 3907,
 3911,
 3915,
 3916,
 3922,
 3926,
 3931,
 3932,
 3938,
 3942,
 3950,
 3952,
 3987,
 3992,
 3996,
 4002,
 4016,
 4033,
 4035,
 4037,
 4042,
 4059,
 4060,
 4083,
 4107,
 4123,
 4129,
 4132,
 4141,
 4157,
 4176,
 4177,
 4197,
 4198,
 4207,
 4212,
 4218,
 4224,
 4226,
 4231,
 4249,
 4259,
 4266,
 4293,
 4300,
 4301,
 4303,
 4316,
 4453,
 4463,
 4476,
 4507,
 4721,
 4731,
 4751,
 4763,
 4810,
 4815,
 4823,
 4835,
 4843,
 4885,
 4899,
 4908,
 4951,
 5006,
 5054,
 5064,
 5135,
 5209,
 5214,
 5306,
 5353,
 5397,
 5408,
 5435,
 5479,
 5515,
 5523,
 5552,
 5571,
 5585,
 5641,
 5667,
 5695,
 5705,
 5719,
 5901,
 5960,
 5964,
 5994,
 6102,
 6103,
 6110,
 6136,
 6155,
 6178,
 6186,
 6187,
 6193,
 6235,
 6296,
 6299,
 6332,
 6358,
 6440,
 6456,
 6466,
 6476,
 6525,
 6574,
 6578,
 6579,
 6581,
 6660,
 6731,
 6734,
 6994,
 7006,
 7011,
 7036,
 7053,
 7066,
 7072,
 7123,
 7126,
 7171,
 7248,
 7267,
 7332,
 7394,
 7543,
 7559,
 7562,
 7633,
 7637,
 7642,
 7665,
 7667,
 7712,
 7782,
 7790,
 7803,
 7820,
 7834,
 7863,
 7990,
 8066,
 8157,
 8170,
 8205,
 8262,
 8274,
 8415,
 8417,
 8432,
 8454,
 8456,
 8467,
 8504,
 8511,
 8566,
 8573,
 8581,
 8660,
 8674,
 8685,
 8727,
 8743,
 8753,
 8755,
 8788,
 8802,
 8804,
 8846,
 8847]

In [57]:
data.drop(delete_index, axis=0, inplace=True)
data.reset_index(drop=True, inplace=True)

In [58]:
data.head()

,순번,영화명,감독,제작사,수입사,배급사,개봉일,영화유형,영화형태,국적,전국,전국 매출액,전국 관객수,서울 매출액,서울 관객수,장르,등급,영화구분
0,1.0,극한직업,이병헌,"(주)어바웃잇,영화사 해그림 주식회사,(주)씨제이이엔엠",NaN,(주)씨제이이엔엠,2019-01-23,개봉영화,장편,한국,1978,139647979516,16264944,31858660536,3638287,코미디,15세이상관람가,일반영화
1,2.0,어벤져스: 엔드게임,"안소니 루소,조 루소",NaN,월트디즈니컴퍼니코리아 유한책임회사,월트디즈니컴퍼니코리아 유한책임회사,2019-04-24,개봉영화,장편,미국,2835,122182694160,13934592,33577136860,3597963,액션,12세이상관람가,일반영화
2,3.0,겨울왕국 2,"크리스 벅,제니퍼 리",NaN,월트디즈니컴퍼니코리아 유한책임회사,월트디즈니컴퍼니코리아 유한책임회사,2019-11-21,개봉영화,장편,미국,2648,114810421450,13747792,28824682580,3225974,애니메이션,전체관람가,일반영화
3,4.0,범죄도시 2,이상용,"주식회사 빅펀치픽쳐스,(주)홍필름,(주)비에이엔터테인먼트",NaN,"주식회사 에이비오엔터테인먼트,메가박스중앙(주)플러스엠",2022-05-18,개봉영화,장편,한국,2498,131293186879,12692947,29072018770,2755693,범죄,15세이상관람가,일반영화
4,5.0,알라딘,가이 리치,NaN,월트디즈니컴퍼니코리아 유한책임회사,월트디즈니컴퍼니코리아 유한책임회사,2019-05-23,개봉영화,장편,미국,1311,106983620359,12555894,30218911039,3377404,어드벤처,전체관람가,일반영화